const fs=require('fs');
const vm=require('vm');
const path=require('path');
const file=path.join(__dirname,'..','design','readuo-first-release.html');
const source=fs.readFileSync(file,'utf8');
const handoffText=fs.readFileSync(path.join(__dirname,'..','docs','readuo-first-release-spec.md'),'utf8')+'\n'+fs.readFileSync(path.join(__dirname,'..','docs','readuo-design-audit.md'),'utf8');
const js=source.match(/<script>([\s\S]*)<\/script>/)[1];
const nodes=new Map();
function node(key){if(!nodes.has(key))nodes.set(key,{innerHTML:'',textContent:'',value:'',hidden:false,checked:false,style:{setProperty(){}},dataset:{}});return nodes.get(key);}
const events={};
const root={querySelector(sel){return node(sel);},addEventListener(n,fn){events[n]=fn;},contains(){return true;},style:{setProperty(){}}};
const context={document:{getElementById(){return root;}},setTimeout(){return 0;},clearTimeout(){},console};
vm.runInNewContext(js,context,{timeout:5000});
const api=root.__readuo;
const ids=new Set(api.screens.map(s=>s.id));
const errors=[];
if(api.state.page!=='login')errors.push('Prototype must start on login');
if(api.screens.length!==117)errors.push('Expected 117 release-one screens/states');
if(ids.size!==api.screens.length)errors.push('Duplicate screen IDs');
let html='';
const inventory=[];
for(const screen of api.screens){
 try{
  api.navigate(screen.id);
  const content=node('#rd-view').innerHTML;
  if(!content||content.includes('undefined'))errors.push(screen.id+': empty or undefined content');
  for(const [,id] of content.matchAll(/data-go="([^"]+)"/g))if(!ids.has(id))errors.push(screen.id+': bad route '+id);
  for(const [,action] of content.matchAll(/data-act="([^"]+)"/g))if(!api.actions[action])errors.push(screen.id+': bad action '+action);
  const locals=[...content.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);
  if(new Set(locals).size!==locals.length)errors.push(screen.id+': duplicate element IDs');
  html+=`<section data-screen="${screen.id}">${content}</section>\n`;
  inventory.push({id:screen.id,group:screen.group,title:screen.title});
 }catch(err){errors.push(screen.id+': '+err.stack);}
}
function assert(condition,message){if(!condition)errors.push(message);}
api.navigate('login');assert(node('#rd-view').innerHTML.includes('Continue with Apple'),'Login missing Apple');
api.navigate('setup');node('#rd-name').value='';api.actions['save-profile']();assert(api.state.page==='setup','Empty name must not continue');node('#rd-name').value='Reader';api.actions['save-profile']();assert(api.state.page==='first-book','Profile setup transition failed');
api.navigate('circle');const before=node('#rd-view').innerHTML;api.actions.like();assert(node('#rd-view').innerHTML!==before,'Like interaction did not render');
api.navigate('compose');node('#rd-post-text').value='A stateful post';api.actions.publish();assert(node('#rd-view').innerHTML.includes('A stateful post'),'Published post not visible');api.navigate('edit-post');node('#rd-post-text').value='An edited post';api.actions['save-edit']();assert(node('#rd-view').innerHTML.includes('An edited post'),'Edited post not visible');
api.navigate('post');node('#rd-comment').value='A lovely read';api.actions.comment();assert(node('#rd-view').innerHTML.includes('A lovely read'),'Comment not rendered');
api.navigate('review');node('#rd-review-text').value='Draft survives';events.input({target:{id:'rd-review-text',value:'Draft survives'}});events.click({target:{closest(){return {dataset:{rating:'4'}};}}});assert(node('#rd-view').innerHTML.includes('Draft survives'),'Review draft lost after rating');
api.navigate('private-confirm');api.actions['make-private']();assert(api.state.visibility==='Private'&&!api.state.auto,'Private shelf must disable auto-post');
api.navigate('enter-code');node('#rd-invite-code').value='ABC';api.actions['find-friend']();assert(api.state.page==='enter-code','Invalid code advanced');node('#rd-invite-code').value='XYZ-123';api.actions['find-friend']();assert(api.state.page==='request-preview','Valid code did not show request preview');
api.navigate('delete-account');node('#rd-delete-check').checked=false;api.actions['delete-account-next']();assert(api.state.page==='delete-account','Deletion missing consent guard');node('#rd-delete-check').checked=true;api.actions['delete-account-next']();assert(api.state.page==='reauth','Deletion missing reauthentication');
assert(api.validateISBN('9780571225392'),'Valid ISBN rejected');assert(!api.validateISBN('9780571225393'),'Invalid ISBN accepted');
assert(api.normalizeISBN('0-571-22539-X')==='9780571225392','Equivalent ISBN-10 did not normalize to ISBN-13');
api.state.friendQuery='';api.state.removedIds=[];api.state.blockedIds=[];api.navigate('friends');
assert([...node('#rd-view').innerHTML.matchAll(/data-friend=/g)].length===8,'Friend list must display 8 matching entries');
events.submit({preventDefault(){},target:{dataset:{search:'friends'},querySelector(){return {value:'Tom'};}}});
assert(node('#rd-view').innerHTML.includes('Tom Bergen')&&!node('#rd-view').innerHTML.includes('Sarah Lin'),'Friend search did not filter correctly');
api.actions['clear-friends']();
const tomButton={dataset:{go:'friend-profile',friend:'tom'}};
events.click({target:{closest(){return tomButton;}}});
assert(node('#rd-view').innerHTML.includes('Tom Bergen')&&!node('#rd-view').innerHTML.includes('Sarah Lin'),'Friend profile identity mismatch');
const discoveredBook={dataset:{go:'friend-book',friend:'sarah',book:'6',remoteShelf:'Desert reads'}};
events.click({target:{closest(){return discoveredBook;}}});
assert(node('#rd-view').innerHTML.includes('Sea of Tranquility')&&node('#rd-view').innerHTML.includes('Sarah Lin owns this book'),'Discovered book identity mismatch');
api.navigate('save-shelf');node('#rd-destination').value='Living room';const libraryCount=api.libraryEntries.length;api.actions['save-book']();assert(api.libraryEntries.length===libraryCount+1,'Saving discovered book did not create exactly one entry');api.navigate('save-shelf');api.actions['save-book']();assert(api.libraryEntries.length===libraryCount+1,'Repeat save duplicated a library entry');
api.state.bookIndex=8;api.navigate('save-shelf');node('#rd-destination').value='Living room';api.actions['save-book']();assert(api.libraryEntries.length===libraryCount+2&&api.libraryEntries.some(entry=>entry.book===8),'Different ISBN for the same title was not saved separately');
api.state.onboarding=false;api.state.manualTitle='Piranesi';api.state.manualAuthor='Susanna Clarke';api.state.manualIsbn='057122539X';api.navigate('manual-confirm');const isbnDuplicateCount=api.libraryEntries.length;api.actions['add-manual']();assert(api.state.page==='scan-duplicate'&&api.libraryEntries.length===isbnDuplicateCount,'Equivalent ISBN-10 did not preserve the existing entry');
api.state.manualTitle='Piranesi';api.state.manualAuthor='Susanna Clarke';api.state.manualIsbn='';api.navigate('manual-confirm');const manualCount=api.libraryEntries.length;api.actions['add-manual']();assert(api.state.page==='manual-possible-duplicate'&&api.libraryEntries.length===manualCount,'No-ISBN possible duplicate did not stop for review');api.actions['confirm-manual-separate']();const manualEntry=api.libraryEntries.at(-1);assert(api.libraryEntries.length===manualCount+1&&manualEntry.entryId&&manualEntry.normalizedIsbn===null,'Reviewed no-ISBN book did not receive a distinct entry ID');
api.state.selectedRequest='priya';api.actions['accept-request']();api.navigate('friends');assert(node('#rd-view').innerHTML.includes('Your friends · 9')&&node('#rd-view').innerHTML.includes('Received · 1'),'Accept request did not update friend/request counts');
api.navigate('manual-confirm');api.navigate('create-shelf');node('#rd-shelf-name').value='QA shelf';node('input[name="visibility"]:checked').value='Friends';api.actions['create-shelf']();assert(api.state.page==='manual-confirm','Create-shelf did not return to manual confirmation');
api.state.selectedFriend='tom';
api.navigate('remove-friend');api.actions['remove-friend']();
assert(!node('#rd-view').innerHTML.includes('Tom Bergen')&&node('#rd-view').innerHTML.includes('Your friends · 8'),'Remove friend did not update list/count');
events.submit({preventDefault(){},target:{dataset:{search:'catalogue-results'},querySelector(){return {value:'No such catalogue title'};}}});assert(api.state.page==='catalogue-no-results','Catalogue empty search did not route to no-results state');
assert(ids.has('delete-account-error')&&ids.has('content-filtered')&&ids.has('catalogue-no-results')&&ids.has('manual-possible-duplicate'),'Required failure/review states missing');
assert(source.includes('Different ISBNs remain separate books'),'Catalogue does not explain ISBN-specific editions');
assert(!/cross-edition book identity remains a pending|whether different editions count as the same book|one entry per user per canonical work/i.test(handoffText),'Handoff still contains pending or canonical-work uniqueness policy');
assert(api.libraryEntries.every(entry=>entry.entryId&&entry.shelf),'Library entries must have a unique ID and exactly one shelf reference');
assert(new Set(api.libraryEntries.map(entry=>entry.entryId)).size===api.libraryEntries.length,'Library entry IDs must be unique');
assert(source.includes('.rd-row>.rd-avatar{flex:0 0 38px;width:38px;height:38px}'),'Avatar must have a fixed circular footprint');
assert(!source.includes('.rd-row>span:first-of-type{flex:1}'),'Old avatar-stretch rule still present');
assert(!source.includes('fetch(')&&!source.includes('XMLHttpRequest')&&!source.includes('WebSocket'),'Unexpected network API');
assert(Buffer.byteLength(source)<1000000,'Fragment exceeds 1MB');
fs.writeFileSync(path.join(__dirname,'readuo-screen-checks.html'),html);
fs.writeFileSync(path.join(__dirname,'readuo-screen-inventory.json'),JSON.stringify(inventory,null,2));
console.log(JSON.stringify({screenCount:api.screens.length,groups:[...new Set(inventory.map(x=>x.group))],bytes:Buffer.byteLength(source),errors},null,2));
if(errors.length)process.exitCode=1;
